remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Cloud Threat Hunter; Real-Time Detection of Brute Force and Malware Attacks
description: [Deploying ELK in the Cloud to Combat Evolving Threats with Automated Incident Response.]

